<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <PackageReference Include="DotNetEnv" Version="3.2.0" />
    <ProjectReference Include="..\ApartmentResidenceManagement.Application\ApartmentResidenceManagement.Application.csproj" />
    <ProjectReference Include="..\ApartmentResidenceManagement.Domain\ApartmentResidenceManagement.Domain.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
